### ISSUE TITLE
formula display issue in markdown split editor

### ISSUE THREAD

**Issue by jingjingjing-666** [shuzijun/markdown-editor#11]
I can't preview math formula in in markdown split editor(good for markdown editor)
I wonder it is normal for others?

ps:
markdown editor version 1.9

**Comment by shuzijun** [comment]
"Markdown Split Editor" is not provided by this plugin, the editor name provided by this plugin is "Markdown Editor"

**Comment by jingjingjing-666** [comment]
@shuzijun 
Thanks for your reply, Markdown Split Editor is one of tab below pycharm(next to markdown editor) when i using markdown editor plugin.
Moreover, you can check it in the following figure:
![image](https://user-images.githubusercontent.com/43951900/134340572-49b2c775-e7fd-44ef-887b-dbb9bede6a94.png)

**Comment by shuzijun** [comment]
"Markdown Split Editor" is provided by the default markdown plugin,[Markdown](https://plugins.jetbrains.com/plugin/7793-markdown)

**Comment by jingjingjing-666** [comment]
Thanks mate! That's the reason why it just got 2.3/5 for default markdown plugin:)
