### ISSUE TITLE
IntelJ pugin did not work

### ISSUE THREAD

**Issue by Happy-ArthurYang** [shuzijun/markdown-editor#114]
After install teh plugin in IntelJ, did not now work, not see any UI of the plugin, nor can edit my .md file.
![image](https://github.com/shuzijun/markdown-editor/assets/113080404/16509f3f-4a88-45f6-afbe-b02d1dfc1ad6)
 
![image](https://github.com/shuzijun/markdown-editor/assets/113080404/315373c7-20c0-4fc9-a4f6-38f0157e023e)

**Comment by Happy-ArthurYang** [comment]
IntelliJ IDEA 2023.3.6 (Ultimate Edition)
Build #IU-233.15026.9, built on March 21, 2024
Licensed to Syngenta / Jie Yang
Subscription is active until September 22, 2024.
Runtime version: 17.0.10+1-b1087.23 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
Non-Bundled Plugins:
  net.coderazzi.aws_codeartifact_maven (3.2.4)
  org.intellij.plugins.hcl (233.13135.65)
  com.jetbrains.space (233.15026.16)
  co.bito.bito-intellij (1.3.0)
  com.shuzijun.markdown-editor (2.0.5)
  MavenRunHelper (4.27.1-IJ2022.2)
  com.intellij.ml.llm (233.15026.9)
  zielu.gittoolbox (500.2.2+233)
  aws.toolkit (2.14-233)
Kotlin: 233.15026.9-IJ

**Comment by shuzijun** [comment]
<img width="811" alt="image" src="https://github.com/shuzijun/markdown-editor/assets/27667179/59e9493b-0bd0-4320-bd90-b3522b7b9ec7">

**Comment by Happy-ArthurYang** [comment]
Thanks a lot
