### ISSUE TITLE
大纲点击没有导航效果;  展示页面和原始内容没有同步滚动

### ISSUE THREAD

**Issue by lxk696** [shuzijun/markdown-editor#13]
大纲点击没有导航效果;  展示页面和原始内容没有同步滚动

**Comment by lxk696** [comment]
intellij 2021.2.2  ultimate edition

**Comment by shuzijun** [comment]
参考问题[issues](https://github.com/Vanessa219/vditor/issues/1001)， 目前高度为自适应，大纲点击无法跳转。
前期指定过高度，但是出现了无法跟随窗口大小变化的问题。
可以先参考[自定义样式](https://github.com/shuzijun/markdown-editor/blob/main/assets/CustomStyle_ZH.md),同步下模板，然后在
https://github.com/shuzijun/markdown-editor/blob/05ae808e51501779e1117b5cef858b38534d3dae/template/default.html#L220
的下方增加
```
"height":document.documentElement.clientHeight, 
```
之后重新打开文件。
