### ISSUE TITLE
请问依赖的 JCEF 要怎么安装?

### ISSUE THREAD

**Issue by hello-soon** [shuzijun/markdown-editor#14]
![image](https://user-images.githubusercontent.com/62131847/135192142-87a1fb19-d52c-4666-845e-7ef887231d14.png)

**Comment by shuzijun** [comment]
插件已经限定版本为2020.2+,除android studio外，其他产品是默认开启JCEF的。
如果修改过产品的运行时依赖的jre,需要恢复成默认的，修复方法参考[Selecting-the-JDK-version-the-IDE-will-run-under](https://intellij-support.jetbrains.com/hc/en-us/articles/206544879-Selecting-the-JDK-version-the-IDE-will-run-under).
如果通过修改配置禁用了JCEF，可以通过以下操作开启:**Help** -> **Find Action..**,在输入框中输入**ide.browser.jcef.enabled**。
android studio用户可以参考https://github.com/shuzijun/markdown-editor/issues/4#issuecomment-889752419 开启
