### ISSUE TITLE
Not Support JCEF: Your environment does not support JCEF, cannot use Markdown Editor

### ISSUE THREAD

**Issue by Morons** [shuzijun/markdown-editor#22]
Not Support JCEF: Your environment does not support JCEF, cannot use Markdown Editor 

Ref: [https://plugins.jetbrains.com/docs/intellij/jcef.html](JCEF - Java Chromium Embedded Framework)

Android Studio Arctic Fox | 2020.3.1 Patch 3
Build #AI-203.7717.56.2031.7784292, built on October 1, 2021
Runtime version: 11.0.10+0-b96-7249189 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 12
Registry: external.system.auto.import.disabled=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.shuzijun.markdown-editor, org.jetbrains.kotlin

**Comment by shuzijun** [comment]
reference #4

**Comment by Morons** [comment]
People want it easy, **fix it** get rid of this issue once and for all
Why do people need to jump loops and go through extra afford!!, they will just uninstall and forget about it.
