### ISSUE TITLE
no work 

### ISSUE THREAD

**Issue by qssq** [shuzijun/markdown-editor#24]
jcef问题解决了，可是还是不生效， 怎么强行开启，有没有快捷键

**Comment by shuzijun** [comment]
描述下具体现象

**Comment by qssq** [comment]
就是不识别，也不报错，而且后面识别了，也不是识别到这个插件，而是默认的，我把默认卸载掉，就提示安装，安装选项里面也只有默认的。

**Comment by qssq** [comment]
![Uploading image.png…]()
我用的是android studio.

**Comment by qssq** [comment]
![image](https://user-images.githubusercontent.com/14260426/142572677-45e5319e-d7e6-4367-95d0-6030b9be1f3d.png)

**Comment by qssq** [comment]
![image](https://user-images.githubusercontent.com/14260426/142572817-cebddcf1-f389-4a49-bab3-d3d9221b208e.png)
我任意创建一个类型，也找不到这个插件的方式打开。

**Comment by qssq** [comment]
就算启用了默认的，底部也没有诸如此类的菜单

**Comment by shuzijun** [comment]
需要安装默认的markdown插件，目前插件的工作形式是以一个附属编辑器展示的。
安装完成以后，打开md文件，在编辑器的下方会出现markdown editor，选择这个编辑器就行了。
可以看下首页的git，有使用的过程

**Comment by qssq** [comment]
一样的，没有，默认的安装和没安装效果都一样，下面没有任何东西

**Comment by shuzijun** [comment]
提供一下打开md文件后，整个界面的截图

**Comment by qssq** [comment]
ReadMe.md no work but other md is work...

**Comment by qssq** [comment]
这个问题非常有意思了，我觉得可以弄成识别md后缀外可以还支持其他后缀或者支持使用某种方式打开。

**Comment by qssq** [comment]
已经搞好了，我重新选择这个文件的类型就生效了。。
