### ISSUE TITLE
只装这个插件不可以用，必须同时安装 JB 的 markdown 插件才可以用。

### ISSUE THREAD

**Issue by Vixb1122** [shuzijun/markdown-editor#26]
1. Android Studio
2. 下载支持 JCEF 的 jbr ，更名为 jre，替换掉 Android Studio 根目录的同名文件夹
3. 安装本插件，无法使用
4. 同时安装 JB 的 markdown 插件，可以使用了
![image](https://user-images.githubusercontent.com/17810492/144543221-89c6b0ab-215a-4c78-b1ed-b7907749605a.png)
![image](https://user-images.githubusercontent.com/17810492/144543322-a9ba3b66-9cb8-4257-921f-b44e22676ec7.png)

**Comment by shuzijun** [comment]
目前插件的编辑器对文件的操作有限，原生编辑器里的一些菜单都无法使用，在完善之前还是需要配合markdown 插件使用

**Comment by Vixb1122** [comment]
> 目前插件的编辑器对文件的操作有限，原生编辑器里的一些菜单都无法使用，在完善之前还是需要配合markdown 插件使用

了解
