### ISSUE TITLE
Dropdown menu "more" has transparent background

### ISSUE THREAD

**Issue by Zeratoxx** [shuzijun/markdown-editor#29]
The dropdown menu "more" in the menubar of the WYSIWYG mode is transparent and the text of the file and the menu labels are overlapping.
![grafik](https://user-images.githubusercontent.com/35294329/145404215-d81dd42a-6345-4624-a917-ddb070e060f6.png)

**Comment by shuzijun** [comment]
Same problem as #29, the theme color is not obtained correctly.
