### ISSUE TITLE
AndroidStudio 图片预览失败

### ISSUE THREAD

**Issue by Heart-Beats** [shuzijun/markdown-editor#37]
![image](https://user-images.githubusercontent.com/33248551/148526511-4093b36f-57c2-4b2b-afba-9f6fe8f2005c.png)
如上图所示，图片预览失败，环境如下：
![image](https://user-images.githubusercontent.com/33248551/148526771-533cb43e-4eba-4e03-b045-7caf53de1175.png)
请大佬确认一下是啥原因

**Comment by shuzijun** [comment]
图片的路径是什么?

**Comment by Heart-Beats** [comment]
路径是 https://github.com/netease-im/NIM_Resources/blob/master/Android/Images/uikit_struct.png，我大概清楚原因是啥了，这个地址对应的是 github 上的页面并不是实际图片地址，大佬可以对这种情况进行兼容处理一下吗？
真实的图片地址为： https://raw.githubusercontent.com/netease-im/NIM_Resources/master/Android/Images/uikit_struct.png

**Comment by shuzijun** [comment]
是这个图片路径限制了加载，没办法兼容，可以在日志中看到
```
Cross-Origin Read Blocking (CORB) blocked cross-origin response https://github.com/netease-im/NIM_Resources/blob/master/Android/Images/uikit_struct.png? 
```

**Comment by Heart-Beats** [comment]
![image](https://user-images.githubusercontent.com/33248551/148530519-a0d56f32-9940-4877-b687-2fdd44a9055d.png)
我的意思是把github上的图片实际加载地址转换为上图中的类似格式，不知道能不能实现，我不太清楚您的插件针对 markdown 的解析之前是否可以修改相关数据

**Comment by shuzijun** [comment]
不会针对链接做这种转换的

**Comment by Heart-Beats** [comment]
好的，那我就把这个问题给关闭了

**Comment by BIGMONK** [comment]
> 是这个图片路径限制了加载，没办法兼容，可以在日志中看到
> 
> ```
> Cross-Origin Read Blocking (CORB) blocked cross-origin response https://github.com/netease-im/NIM_Resources/blob/master/Android/Images/uikit_struct.png? 
> ```

请问日志怎么看的

**Comment by shuzijun** [comment]
> 请问日志怎么看的
编辑器上右键 Open Devtools ，打开的是浏览器的开发者工具
