### ISSUE TITLE
Code block is doubled in Instant Rendering Mode

### ISSUE THREAD

**Issue by Zeratoxx** [shuzijun/markdown-editor#40]
Hello!

When working in instant rendering mode, code blocks are getting doubled displayed when working on them, I guess that is a bug.

![grafik](https://user-images.githubusercontent.com/35294329/150804562-fee451c7-28de-45a9-9513-d5fc436a6d49.png)
![grafik](https://user-images.githubusercontent.com/35294329/150804269-2ec70527-8b61-441a-ac9a-f5b1a2654490.png)

**Comment by Zeratoxx** [comment]
Also: I cannot click on the closing ``` quotation marks to edit the line.

**Comment by shuzijun** [comment]
This is a display form, divided into two areas, the upper part is the editing area, and the lower part is the real-time rendering display area. If it is a graph, it may be more intuitive to understand.
![image](https://user-images.githubusercontent.com/27667179/150896319-bc996079-bf91-4663-8734-2df8b2a2d23b.png)

**Comment by Zeratoxx** [comment]
I see. Hmm, I guess that was not clear enough so that I understood it 😅
