### ISSUE TITLE
Tables not formatted in Raw Editor Correctly

### ISSUE THREAD

**Issue by cwginac** [shuzijun/markdown-editor#50]
When editing a table, and then looking at the raw source, the table is not formatted correctly.  The second row (the row with hyphens) is not aligned with the rest of the table.

For example:
```
| Section | Key         | Value         | Description |
| --------- | ------------- | --------------- | ------------- |
| example | example_key | example_value | ex_desc     |
```
I believe it is not accounting for the spaces before and after the hyphens, essentially making that section two characters wider than it should be.

The number of hyphens should be `(length of longest cell - 2)`

**Comment by shuzijun** [comment]
waiting for dependencies to update
