### ISSUE TITLE
切换编辑模式会导致文件状态发生改变

### ISSUE THREAD

**Issue by lunfangyu** [shuzijun/markdown-editor#62]
![image_20220802153013](https://user-images.githubusercontent.com/41062458/182320392-42ed1afb-da10-4039-9e0b-a184be8a3d9b.gif)
如图，在.md文件已全部提交git的情况下，重新打开.md文件，然后点击“切换编辑模式”；模式完成切换后，没对文件做任何输入改动，但从文件标题的颜色变化显示：文件已发生改动。不知这算不算个小BUG

**Comment by ddv12138** [comment]
+1，插件会擅自改动文件导致git状态改变
