### ISSUE TITLE
装完插件之后ESC键不好用了

### ISSUE THREAD

**Issue by qq253498229** [shuzijun/markdown-editor#65]
比如以前我使用git的Show diff功能查看版本变化窗口，这时候按ESC键可以快速关闭这个窗口。
但是装了这个插件之后，按ESC键无法关闭了，需要按Command+w才能关闭。

IDE信息：
```
WebStorm 2022.2
Build #WS-222.3345.108, built on July 23, 2022
Runtime version: 17.0.3+7-b469.32 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.4
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Non-Bundled Plugins:
    org.asciidoctor.intellij.asciidoc (0.37.36)
```

**Comment by shuzijun** [comment]
如发生快捷键冲突，可以参考文档移除或修改插件默认快捷键 https://www.jetbrains.com/help/webstorm/settings-keymap.html

**Comment by mcxinyu** [comment]
这种情况还是建议说明下，我也是这个问题找了好久。

**Comment by iamqiz** [comment]
真的哎, 是这个插件的这个快捷键导致的:  删掉即可解决
![Snipaste_2022-12-05_12-20-40](https://user-images.githubusercontent.com/48077521/205548856-e6766d1a-3765-4fa1-8886-e1dbd96debee.png)
