### ISSUE TITLE
本地图片复制粘贴自动完成 ctrl c + ctrl v

### ISSUE THREAD

**Issue by zb315044652** [shuzijun/markdown-editor#68]
### 你在什么场景下需要该功能？

当我上传图片时，ctrl c + ctrl v的时候，会弹出下面的提示框：
![image](https://user-images.githubusercontent.com/17883776/188391456-0f9c5b48-c997-45e1-87bf-4144a582c98e.png)

如果添加过几次，还需要手动修改文件名称，不然会出现重复
![image](https://user-images.githubusercontent.com/17883776/188391667-4d9f4b2c-cb01-4712-a7fb-4b70fa35da5e.png)

中间增加了好几步，操作，能否使这个过程一步自动完成。只需要提前配置好文件夹，粘贴的图片按照一定的格式（时间戳.jpg）复制

另外本地图上复制粘贴，复制到的文件夹路径能否支持可配置

### 描述最优的解决方案 

存储的文件夹可配置，文件自动生成名称，ctrl c + ctrl v自动完成本地图片插入

**Comment by shuzijun** [comment]
File | Settings | Tools | Markdown Editor

**Comment by zb315044652** [comment]
之前没有找到这个配置，手动修改名称已经可以用时间戳自动取代了，现在还有个问题就是，任然需要二次确认，如果能改成自动确认就完美了，
![image](https://user-images.githubusercontent.com/17883776/189861303-e5455c78-ea7b-48a3-8911-745790db6c29.png)

减少一部点击确认的的操作

**Comment by shuzijun** [comment]
> 之前没有找到这个配置，手动修改名称已经可以用时间戳自动取代了，现在还有个问题就是，仍然需要二次确认，如果能改成自动确认就完美了， ![image](https://user-images.githubusercontent.com/17883776/189861303-e5455c78-ea7b-48a3-8911-745790db6c29.png)
> 
> 减少一部点击确认的的操作

这一步是明确文件存储路径与文件名，进行二次确认。

**Comment by shuzijun** [comment]
没有计划去掉这个确认信息。可以Fork之后修复下面的代码，去掉确认框。
https://github.com/shuzijun/markdown-editor/blob/9d143669257c5b70e0cbb7035ca2e8f42b4b2e45/src/main/java/com/shuzijun/markdown/controller/UploadFileController.java#L72
