### ISSUE TITLE
markdown-editor 的1.9版本、LeetCode Editor的7.3版本，都出现Not Support JCEF错误，请问如何解决？

### ISSUE THREAD

**Issue by lelelongwang** [shuzijun/markdown-editor#7]
markdown-editor 的1.9版本、LeetCode Editor的7.3版本，都出现Not Support JCEF错误，请问如何解决？

![image](https://user-images.githubusercontent.com/18341579/130029316-2934977f-f1f4-4b58-a272-81e1392abe30.png)

**Comment by lelelongwang** [comment]
对应的AndroidStudio版本为最新版本，版本号如下图：
![image](https://user-images.githubusercontent.com/18341579/130029964-1f0434d9-4be3-45f8-9e5f-6ec555944dba.png)

**Comment by shuzijun** [comment]
参考https://github.com/shuzijun/markdown-editor/issues/4
