### ISSUE TITLE
Menu bar disappears

### ISSUE THREAD

**Issue by winston-zillow** [shuzijun/markdown-editor#72]
It is unclear what steps can reproduce this problem, but I encountered it twice after using it for an hour. I had to restart Intellij IDEA and the menu bar reappear after restarting. 
<img width="191" alt="Screen Shot 2022-10-07 at 3 34 45 PM" src="https://user-images.githubusercontent.com/26907141/194672010-b2fc42a5-a43c-442a-8a8a-741bb18fb908.png">
 If I just close the editor tab and reopen, the menu bar area shows up without the icons.
<img width="192" alt="Screen Shot 2022-10-07 at 3 40 12 PM" src="https://user-images.githubusercontent.com/26907141/194672077-d9f9a620-e7a8-4987-9d55-adda665058dd.png">

**Comment by shuzijun** [comment]
Right-click menu, open the console, check for errors。
![image](https://user-images.githubusercontent.com/27667179/194704203-67a32935-bdd4-4814-9bab-7b181051bfcc.png)
<img width="652" alt="image" src="https://user-images.githubusercontent.com/27667179/194704216-b6832863-1d45-4482-ac58-2ab855d90886.png">

**Comment by winston-zillow** [comment]
I saw one error but I don't think it relates to this problem because the error is there as soon as I open the markdown file and the menu bar is showing:
```
2index.min.js?_ijt=bi9sfgng8p27749iirdk7jh9m2:1 Uncaught TypeError: Cannot read properties of null (reading 'classList')
    at index.min.js?_ijt=bi9sfgng8p27749iirdk7jh9m2:1:237981
    at NodeList.forEach (<anonymous>)
    at e.addCaret (index.min.js?_ijt=bi9sfgng8p27749iirdk7jh9m2:1:237939)
    at e.addToUndoStack (index.min.js?_ijt=bi9sfgng8p27749iirdk7jh9m2:1:235590)
    at index.min.js?_ijt=bi9sfgng8p27749iirdk7jh9m2:1:177274
```

however, I found easy to reproduce steps:
1. open a markdown file, seeing the menu bar
2. go to some other files such as .py files
3. go back to the markdown editor tab
4. now the menu bar is mostly hidden
5. close the markdown file
6. open the markdown file again and the menu bar reappears

**Comment by shuzijun** [comment]
This problem has been reproduced.
The status bar is obscured because the size of the editor has changed, trying to fix it.
