### ISSUE TITLE
问题：在大纲中点击标题，不跳转指定内容

### ISSUE THREAD

**Issue by sunnyAfterSnow** [shuzijun/markdown-editor#75]
具体情况是这样，点击more...后的outline，左侧出现大纲，

首先，初始情况下（默认情况下）outline点击标题跳转内容有效，

然后，当你点击File | Settings | Tools | Markdown Editor ,在右侧的template path旁点击SYNC，需要自定义配置文件时，大纲中点击标题跳转内容失效。

最后，你在template path里，将assets目录删掉，或者重命名为别的名字（例如assets_bak），大纲的点击效果又恢复正常

我的环境：IDE：WebStorm 2022.2.2，通过插件市场安装

**Comment by shuzijun** [comment]
重新点击SYNC同步一下，模版文件已同步到最新

**Comment by sunnyAfterSnow** [comment]
谢谢，目前这个问题已经弄好，我重启了下电脑，然后SYNC同步一下。
