### ISSUE TITLE
复制图片默认的文件路径

### ISSUE THREAD

**Issue by itweixiang** [shuzijun/markdown-editor#82]
### 现象描述

粘贴图片的时候，是默认放在../assets路径下面了。查了下配置，没有看到相关的参数可以设置。

### 代码

看了下代码，应该是在这个类里面设置了默认值

![图片](https://user-images.githubusercontent.com/40189074/211236666-f9f972e0-2838-44c4-83a0-7fd54218d6d0.png)

### 修改

我在idea的安装目录，手动给idea64.exe.vmoptions和idea.properties这两个文件，手动加上了配置
```properties
markdown.editor.editorAssetsPath=images
```

但复制图片的时候，还是assets，这个是为什么呢？

**Comment by shuzijun** [comment]
配置路径: File | Settings | Tools | Markdown Editor

**Comment by itweixiang** [comment]
配置路径: File | Settings | Tools | Markdown Editor

这个里面的选项，看不出来要怎么配置呀，有详细点的说明吗？

**Comment by shuzijun** [comment]
<img width="870" alt="image" src="https://user-images.githubusercontent.com/27667179/211308511-806db598-86d6-4ca2-b3ea-8ba7c891ea95.png">

**Comment by itweixiang** [comment]
应该是我使用的IDEA版本比较低，然后没出现这个配置
