### ISSUE TITLE
怎么隐藏 toolbar

### ISSUE THREAD

**Issue by youngkaaa** [shuzijun/markdown-editor#86]
首先感谢这个很棒的项目。
请教下怎么隐藏顶部的toolbar。看了[该项目](https://github.com/Vanessa219/vditor/blob/master/README_en_US.md)的介绍，其中有：options.toolbarConfig  可以指定hide 值来控制 toolbar 的隐藏和显示。
因此请问下当前项目有无办法可以低成本的隐藏掉toolbar，还是说我得自己fork二次编译修改呢？
感谢

**Comment by shuzijun** [comment]
参考#85 修改模版里的toolbarConfig即可

**Comment by youngkaaa** [comment]
好的已解决。感谢回复
