### ISSUE TITLE
In PyCharm 2021.2.1 Does is not associated with MARKDOWN files

### ISSUE THREAD

**Issue by ipcoder** [shuzijun/markdown-editor#9]
I have disabled bundled Markdown plugin.
Now Markdown disappeared from list of file types. 
Also when open .MD files suggests to enable the bundled Markdonb plugin.

**Comment by shuzijun** [comment]
There is no need to uninstall the default markdown plugin. The editor of the current plugin appears after the default editor.

**Comment by ipcoder** [comment]
Thanks
