### ISSUE TITLE
Not support github markdown emoji 

### ISSUE THREAD

**Issue by imtianx** [shuzijun/markdown-editor#98]
`:alarm_clock:` : :alarm_clock: 

the complete list is [here](https://gist.github.com/rxaviers/7360908#file-gistfile1-md)

**Comment by shuzijun** [comment]
Supported references: [emoji_map](https://github.com/88250/lute/blob/master/parse/emoji_map.go)

**Comment by imtianx** [comment]
It can't preview on Android studio.
![temp](https://github.com/shuzijun/markdown-editor/assets/13366797/a25eca60-fb5b-4a71-922f-8bade28bf6d5)

**Comment by shuzijun** [comment]
<img width="827" alt="image" src="https://github.com/shuzijun/markdown-editor/assets/27667179/a39ecd16-05d7-40e5-a7a6-d5f2a507e32c">

**Comment by imtianx** [comment]
Ok.
